name: pkgcheck
description: Run pkgcheck over an ebuild repository
inputs:
  args:
    description: Arguments to pass to pkgcheck
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Cache pkgcheck
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pkgcore
          ~/.cache/pkgcheck
        key: pkgcheck

    - name: Run pkgcheck
      uses: docker://ghcr.io/pkgcore/pkgcheck:latest
      with:
        entrypoint: /usr/bin/bash
        args: >
          -c "
          runner() { echo \"::group::${1}\"; shift 1; \"$@\"; local exit=$?; echo; echo \"::endgroup::\"; return $exit; } ;
          runner \"Sync gentoo repo\" pmaint sync gentoo || exit 1 ;
          runner \"Update repo metadata\" pmaint regen --dir ~/.cache/pkgcheck/repos . ;
          runner \"Marking workspace safe for git\" git config --global --add safe.directory '*' ;
          runner \"Run pkgcheck\" pkgcheck --color y ci --failures ~/failures.json --exit GentooCI ${{ inputs.args }} ;
          scan_exit_status=$? ;
          pkgcheck replay --color y ~/failures.json ;
          exit $scan_exit_status
          "
